services:

    #Booking Create subscriber
    cocorico.booking.create.subscriber:
        class: Cocorico\CoreBundle\Subscriber\BookingCreateSubscriber
        arguments:
            - "@cocorico.booking.manager"
        tags:
            - { name: kernel.event_subscriber}

    #Booking Created subscriber
    cocorico.booking_new.created.subscriber:
        class: Cocorico\CoreBundle\Subscriber\BookingCreatedSubscriber
        arguments:
            - "@cocorico_paypal_ap"
            - "@lexik_currency.converter"
            - "@session"
            - %cocorico.currency%
        tags:
            - { name: kernel.event_subscriber}

    #Booking Pay subscriber
    cocorico.booking_pay.subscriber:
        class: Cocorico\CoreBundle\Subscriber\BookingPaySubscriber
        arguments:
            - "@cocorico_paypal_ap"
            - "@doctrine.orm.entity_manager"
            - "@cocorico.payment.paypal.payment_detail_manager"
        tags:
            - { name: kernel.event_subscriber}

    #Booking Refund subscriber
    cocorico.booking_payin_refund.subscriber:
        class: Cocorico\CoreBundle\Event\BookingPayinRefundSubscriber
        arguments:
            - "@cocorico.booking_payin_refund.manager"
        tags:
            - { name: kernel.event_subscriber}

    #Booking Validate subscriber
    cocorico.booking_validate.subscriber:
        class: Cocorico\CoreBundle\Event\BookingValidateSubscriber
        arguments:
            - "@cocorico.booking_bank_wire.manager"
        tags:
            - { name: kernel.event_subscriber}

    #BookingBankWire  subscriber
    cocorico.booking_bank_wire.subscriber:
        class: Cocorico\CoreBundle\Event\BookingBankWireSubscriber
        arguments:
            - "@cocorico.booking_bank_wire.manager"
            - "@logger"
        tags:
            - { name: kernel.event_subscriber}